language: haskell

env:
  - GHCVER=7.8.3

before_install:
  - |
    if [ q$GHCVER = q$(ghc --numeric-version) ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
      export CABAL=cabal-1.18
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
    fi
  - wget http://libsdl.org/release/SDL2-2.0.6.tar.gz -O - | tar xz
  - cd SDL2-2.0.6 && ./configure && make -j && sudo make install && cd ..
  - cabal install --only-d

script:
  - $CABAL configure
  - $CABAL build

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-game"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
